Boolean/exercises/dotnet_exercises/la-mia-pizzeria-crud-mvc-camillo/la-mia-pizzeria-static/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using la_mia_pizzeria_static.Models;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace la_mia_pizzeria_static.Controllers
{
	[Authorize(Roles = "Admin, User")]
	public class PizzaController : Controller
    {
		private readonly ILogger<PizzaController> _logger;
		private readonly PizzaContext _context;


		public PizzaController(ILogger<PizzaController> logger, PizzaContext context)
		{
			_logger = logger;
			_context = context;
			System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
			customCulture.NumberFormat.NumberDecimalSeparator = ".";
			System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;
		}

		public IActionResult Index()
        {
            var pizzas = _context.Pizzas
                .Include(p=>p.Category)
                .ToArray();

            return View(pizzas);

        }

		public IActionResult Privacy()
        {
            return View();
        }

		public IActionResult Detail(int id)
        {
            var pizza = _context.Pizzas
                .Include (p => p.Category)
				.Include(p => p.Ingredients)
				.SingleOrDefault(p => p.Id == id);

            if (pizza is null)
            {
                return NotFound($"Pizza with id {id} not found.");
            }

            return View(pizza);
        }

		[Authorize(Roles = "Admin")]
		public IActionResult Create()
        {
            var formModel = new PizzaFormModel()
            {
                Categories = _context.Categories.ToArray(),
				Ingredients = _context.Ingredients.Select(i => new SelectListItem(i.Name, i.Id.ToString())).ToArray()
			};

            return View(formModel);
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaFormModel form)
        {
            if (!ModelState.IsValid)
            {
                form.Categories = _context.Categories.ToArray();
				form.Ingredients = _context.Ingredients.Select(i => new SelectListItem(i.Name, i.Id.ToString())).ToArray();

				return View(form);
            }

			form.Pizza.Ingredients = form.SelectedIngredients.Select(si => _context.Ingredients.First(i => i.Id == Convert.ToInt32(si))).ToList();

			_context.Pizzas.Add(form.Pizza);
			_context.SaveChanges();

			return RedirectToAction("Index");   
        }

		[Authorize(Roles = "Admin")]
		public ActionResult Update(int id)
        {
			var pizza = _context.Pizzas.Include(p => p.Ingredients).SingleOrDefault(p => p.Id == id);

			if (pizza is null)
			{
				return NotFound($"Pizza with id {id} not found.");
			}

			var formModel = new PizzaFormModel
			{
				Pizza = pizza,
				Categories = _context.Categories.ToArray(),
				Ingredients = _context.Ingredients.ToArray().Select(i => new SelectListItem(
					i.Name,
					i.Id.ToString(),
					pizza.Ingredients!.Any(_i => _i.Id == i.Id))
				).ToArray()
			};

			formModel.SelectedIngredients = formModel.Ingredients.Where(i => i.Selected).Select(i => i.Value).ToList();

			return View(formModel);
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Update(int id, PizzaFormModel form)
		{
			if (!ModelState.IsValid)
			{
				form.Categories = _context.Categories.ToArray();
				form.Ingredients = _context.Ingredients.Select(i => new SelectListItem(i.Name, i.Id.ToString())).ToArray();

				return View(form);
			}

			var savedPizza = _context.Pizzas.Include(p => p.Ingredients).FirstOrDefault(i => i.Id == id);

			if (savedPizza is null)
			{
				return NotFound($"Pizza with id {id} not found.");
			}

			savedPizza.Name = form.Pizza.Name;
			savedPizza.Description = form.Pizza.Description;
			savedPizza.Img = form.Pizza.Img;
			savedPizza.CategoryId = form.Pizza.CategoryId;
			savedPizza.Ingredients = form.SelectedIngredients.Select(si => _context.Ingredients.First(i => i.Id == Convert.ToInt32(si))).ToList();

			_context.SaveChanges();

			return RedirectToAction("Index");

		}

		[Authorize(Roles = "ADMIN")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int id)
		{
			var pizzaToDelete = _context.Pizzas.FirstOrDefault(p => p.Id == id);

			if (pizzaToDelete is null)
			{
				return NotFound($"Pizza with id {id} not found.");
			}

			_context.Pizzas.Remove(pizzaToDelete);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}


	}

}

Boolean/exercises/dotnet_exercises/la-mia-pizzeria-crud-mvc-camillo/la-mia-pizzeria-static/Views/Shared/_Footer.cshtml
<footer>FOOTER</footer>

Boolean/exercises/dotnet_exercises/la-mia-pizzeria-crud-mvc-camillo/la-mia-pizzeria-static/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Pizza")">Pizzeria</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Privacy", "Pizza")">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="@Url.Action("Index", "User")">Admin</a>
                    </li>

				</ul>  
                
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
</header>

Boolean/exercises/dotnet_exercises/la-mia-pizzeria-crud-mvc-camillo/la-mia-pizzeria-static/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Razor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Header")
    </header>
    <div class="container">
        <main role="main" class="w-100">
            @RenderBody()
        </main>
    </div>

    <footer>
        @await Html.PartialAsync("_Footer")
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Boolean/exercises/dotnet_exercises/la-mia-pizzeria-crud-mvc-camillo/la-mia-pizzeria-static/Views/Shared/_Row.cshtml
@model Pizza

@{
    var pizza = Model;
}

<tr>
    <td>@pizza.Id</td>
    <td class="image"><img class="pizza-link-image img-fluid" src="@pizza.Img"></td>
    <td class="title mb-4">
        <a href="@Url.Action("Detail", "Pizza", new { Id = pizza.Id })" class="btn btn-dark">@pizza.Name</a>
    </td>
    <td class="title mb-4">
        <div>@pizza.Price€</div>
    </td>
    <td class="description">@pizza.Description</td>
    <td>@pizza.Category!.Name</td>
    @if (User.IsInRole("Admin"))
    {
        <td>
            <a href="@Url.Action("Update", "Pizza", new { Id = pizza.Id })" class="btn btn-warning">Edit</a>
            <form asp-action="Delete" asp-controller="Pizza" asp-route-id="@pizza.Id">
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    }
</tr>